const BaseComponent = require('./BaseComponent');

class RendererComponent extends BaseComponent {
    async process(data) {
        this.log('Rendering sectioned newsletter...');
        
        // Handle both grouped and flat data structures
        const insights = data.flat || data; // Fallback to flat if no grouping
        const groupedInsights = data.grouped || null;
        const summary = data.summary || null;
        
        const htmlNewsletter = groupedInsights 
            ? this.generateSectionedHTMLNewsletter(groupedInsights, summary)
            : this.generateHTMLNewsletter(insights);
            
        const textNewsletter = groupedInsights 
            ? this.generateSectionedTextNewsletter(groupedInsights, summary)
            : this.generateTextNewsletter(insights);
        
        this.processedCount = insights.length;
        
        return {
            insights: insights,
            grouped: groupedInsights,
            html: htmlNewsletter,
            text: textNewsletter,
            metadata: this.generateMetadata(insights, summary)
        };
    }
    
    generateSectionedHTMLNewsletter(groupedInsights, summary) {
        const date = new Date().toLocaleDateString('en-US', { 
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
        });
        
        // Generate sections HTML
        const sectionsHTML = Object.entries(groupedInsights).map(([sectionName, insights]) => 
            this.generateHTMLSection(sectionName, insights, summary ? summary[sectionName] : null)
        ).join('');
        
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ai.PM Insights - ${date}</title>
    ${this.theme.getCSS()}
</head>
<body>
    <div class="newsletter-container">
        <div class="header">
            <h1>🎯 ai.PM Insights</h1>
            <p class="subtitle">AI-powered intelligence for PM professionals | ${date}</p>
        </div>
        
        <div class="content">
            ${this.generateTableOfContents(groupedInsights, summary)}
            ${sectionsHTML}
        </div>
        
        <div class="footer">
            <p>Generated by ai.PM Insights Engine | Powered by Claude AI</p>
            <p>Quality-focused analysis with anti-hallucination safeguards</p>
        </div>
    </div>
</body>
</html>`;
    }
    
    generateTableOfContents(groupedInsights, summary) {
        const tocItems = Object.entries(groupedInsights).map(([sectionName, insights]) => {
            const sectionSummary = summary ? summary[sectionName] : null;
            const count = insights.length;
            const avgImpact = sectionSummary ? sectionSummary.averageImpact : 'N/A';
            
            return `<li><a href="#${this.getSectionId(sectionName)}">${sectionName}</a> <span class="toc-meta">(${count} insights, ${avgImpact}/10 avg impact)</span></li>`;
        }).join('');
        
        return `
        <div class="table-of-contents">
            <h2>📋 Contents</h2>
            <ul>
                ${tocItems}
            </ul>
        </div>`;
    }
    
    generateHTMLSection(sectionName, insights, sectionSummary) {
        const sectionId = this.getSectionId(sectionName);
        let cardNumber = 1; // Reset numbering for each section
        
        const cardsHTML = insights.map((insight) => 
            this.generateHTMLCard(insight, cardNumber++)
        ).join('');
        
        const summaryHTML = sectionSummary ? `
        <div class="section-summary">
            <span class="summary-stat">📊 ${sectionSummary.count} insights</span>
            <span class="summary-stat">🎯 ${sectionSummary.averageImpact}/10 avg impact</span>
            <span class="summary-stat">🔍 ${sectionSummary.averageConfidence}/10 avg confidence</span>
            ${sectionSummary.needsReview > 0 ? `<span class="summary-stat review-needed">⚠️ ${sectionSummary.needsReview} need review</span>` : ''}
        </div>` : '';
        
        return `
        <div class="newsletter-section" id="${sectionId}">
            <div class="section-header">
                <h2>${sectionName}</h2>
                ${summaryHTML}
            </div>
            <div class="section-content">
                ${cardsHTML}
            </div>
        </div>`;
    }
    
    getSectionId(sectionName) {
        return sectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    }
    
    generateSectionedTextNewsletter(groupedInsights, summary) {
        const date = new Date().toLocaleDateString('en-US', { 
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
        });
        
        // Generate table of contents
        const toc = Object.entries(groupedInsights).map(([sectionName, insights]) => {
            const count = insights.length;
            const avgImpact = summary && summary[sectionName] ? summary[sectionName].averageImpact : 'N/A';
            return `   • ${sectionName} (${count} insights, ${avgImpact}/10 avg impact)`;
        }).join('\n');
        
        // Generate sections
        const sections = Object.entries(groupedInsights).map(([sectionName, insights]) => {
            let cardNumber = 1;
            const cards = insights.map(insight => this.generateTextCard(insight, cardNumber++)).join('\n\n');
            
            const sectionSummary = summary && summary[sectionName] ? summary[sectionName] : null;
            const summaryText = sectionSummary ? `
📊 Section Summary: ${sectionSummary.count} insights | 🎯 ${sectionSummary.averageImpact}/10 avg impact | 🔍 ${sectionSummary.averageConfidence}/10 avg confidence${sectionSummary.needsReview > 0 ? ` | ⚠️ ${sectionSummary.needsReview} need review` : ''}` : '';
            
            return `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${sectionName}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${summaryText}

${cards}`;
        }).join('\n\n');
        
        return `🎯 ai.PM INSIGHTS
AI-powered intelligence for PM professionals | ${date}

📋 CONTENTS:
${toc}

${sections}

Generated by ai.PM Insights Engine | Powered by Claude AI
Quality-focused analysis with anti-hallucination safeguards`;
    }
    
    // ===== EXISTING METHODS (for compatibility) =====
    
    generateHTMLNewsletter(insights) {
        const date = new Date().toLocaleDateString('en-US', { 
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
        });
        
        const cardsHTML = insights.map((insight, index) => 
            this.generateHTMLCard(insight, index + 1)
        ).join('');
        
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ai.PM Insights - ${date}</title>
    ${this.theme.getCSS()}
</head>
<body>
    <div class="newsletter-container">
        <div class="header">
            <h1>🎯 ai.PM Insights</h1>
            <p class="subtitle">AI-powered intelligence for PM professionals | ${date}</p>
        </div>
        
        <div class="content">
            ${cardsHTML}
        </div>
        
        <div class="footer">
            <p>Generated by ai.PM Insights Engine | Powered by Claude AI</p>
            <p>Quality-focused analysis with anti-hallucination safeguards</p>
        </div>
    </div>
</body>
</html>`;
    }
    
    generateHTMLCard(insight, cardNumber) {
        // ✅ SAFE PROPERTY ACCESS WITH DEFAULTS
        const title = insight.title || 'No title available';
        const url = insight.url || '#';
        const tagline = insight.tagline || 'Strategic insights for modern PMOs';
        const audience = insight.targetAudience || 'All PMO Sphere Roles';
        const summary = insight.summary || 'Article provides insights relevant to PMO operations';
        const pmoApplications = insight.pmoApplications || 'Consider applications for PMO strategic planning';
        const strategicValue = insight.strategicValue || 'Organizations report positive results';
        const formattedFactors = insight.formattedFactors || 'Factors not available';
        const impactScore = insight.impactScore || 7;
        const readTime = insight.readTime || 3;
        const tags = insight.tags || ['PMO Strategy', 'Process Improvement'];
        const reviewFlag = insight.reviewFlag || false;
        const reviewNote = insight.reviewNote || '';
        
        const reviewNoteHTML = reviewFlag ? 
            `<div class="review-note">⚠️ <strong>Review Note:</strong> ${reviewNote}</div>` : '';
        
        return `
        <div class="insight-card">
            <div class="card-header">
                <h3>🎯 ai.PM INSIGHTS #${cardNumber}</h3>
            </div>
            
            <div class="card-body">
                <div class="tagline">💡 ${tagline}</div>
                
                <div class="target-audience">
                    <strong>👥 Target Audience:</strong> ${audience}
                </div>
                
                <h4 class="article-title">
                    <a href="${url}" target="_blank" rel="noopener noreferrer">📰 ${title} →</a>
                </h4>
                
                <div class="summary">${summary}</div>
                
                <div class="applications">
                    <strong>PMO Applications:</strong> ${pmoApplications}
                </div>
                
                <div class="strategic-value">
                    <strong>Strategic Value:</strong> ${strategicValue}
                </div>
                
                <div class="decision-framework">
                    <h5>Quick Decision Framework:</h5>
                    <div class="factors">${formattedFactors}</div>
                </div>
                
                <div class="metadata">
                    📈 <strong>PMO Impact: ${impactScore}/10</strong> | 
                    ⏱️ <strong>${readTime} min read time</strong> | 
                    🏷️ <strong>${tags.join(', ')}</strong>
                </div>
                
                ${reviewNoteHTML}
            </div>
        </div>`;
    }
    
    generateTextNewsletter(insights) {
        const date = new Date().toLocaleDateString('en-US', { 
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
        });
        
        const textCards = insights.map((insight, index) => 
            this.generateTextCard(insight, index + 1)
        ).join('\n---\n\n');
        
        return `🎯 ai.PM INSIGHTS
AI-powered intelligence for PM professionals | ${date}

${textCards}

Generated by ai.PM Insights Engine | Powered by Claude AI
Quality-focused analysis with anti-hallucination safeguards`;
    }
    
    generateTextCard(insight, cardNumber) {
        // ✅ SAFE PROPERTY ACCESS WITH DEFAULTS
        const title = insight.title || 'No title available';
        const url = insight.url || '#';
        const tagline = insight.tagline || 'Strategic insights for modern PMOs';
        const audience = insight.targetAudience || 'All PMO Sphere Roles';
        const summary = insight.summary || 'Article provides insights relevant to PMO operations';
        const pmoApplications = insight.pmoApplications || 'Consider applications for PMO strategic planning';
        const strategicValue = insight.strategicValue || 'Organizations report positive results';
        const formattedFactors = insight.formattedFactors || 'Factors not available';
        const impactScore = insight.impactScore || 7;
        const readTime = insight.readTime || 3;
        const tags = insight.tags || ['PMO Strategy', 'Process Improvement'];
        const reviewFlag = insight.reviewFlag || false;
        const reviewNote = insight.reviewNote || '';
        
        const reviewNoteText = reviewFlag ? `\n⚠️ **Review Note:** ${reviewNote}` : '';
        
        return `┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ 🎯 ai.PM INSIGHTS #${cardNumber}                          ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

**💡 ${tagline}**

**👥 Target Audience:** ${audience}

**📰 [${title} →](${url})**

${summary}

**PMO Applications:** ${pmoApplications}

**Strategic Value:** ${strategicValue}

**Quick Decision Framework:**
${formattedFactors}

📈 **PMO Impact: ${impactScore}/10** | ⏱️ **${readTime} min read time** | 🏷️ **${tags.join(', ')}**${reviewNoteText}`;
    }
    
    generateMetadata(insights, summary) {
        const base = {
            totalInsights: insights.length,
            needReview: insights.filter(i => i.reviewFlag || false).length,
            highConfidence: insights.filter(i => (i.confidenceScore || 0) >= 8).length,
            averageConfidence: insights.reduce((sum, i) => sum + (i.confidenceScore || 0), 0) / insights.length,
            contentTypes: this.getContentTypeDistribution(insights)
        };
        
        if (summary) {
            base.sections = summary;
        }
        
        return base;
    }
    
    getContentTypeDistribution(insights) {
        const types = {};
        insights.forEach(insight => {
            const type = insight.contentType || 'Unknown';
            types[type] = (types[type] || 0) + 1;
        });
        return types;
    }
}

module.exports = RendererComponent;